@startuml

#ccc:Config::$configMap = Map();

start

repeat
:Config::define(k, v);

if (defined(k)) then (true)
  :throw ConstantAlreadyDefinedException;
  stop
else (false)
  #ccc:Config::$configMap->put(k, v);
endif

repeat while (config complete?)

:Config::apply();

if (any((defined(k) or constant(k) !== v) for k, v in Config::$configMap)?   ) then (true)
  :throw ConstantAlreadyDefinedException;
  stop
else (false)
  #ccc:define(k, v) for k, v in Config::$configMap;
endif

stop

@enduml
