@startuml

start

:define('WP_ENV', 'E');

:execute application.php;
note right
  Config::define(k, v) for k, v in
  {WP_HOME: ..., DB_HOST: ..., WP_DEBUG_DISPLAY: false, ...}
end note

if (file_exists config/environments/E.php) then (yes)
  :execute config file E.php;
  note left
    Config::define(?, ?)...
    ini_set(?, ?)...
    some_method(?)...
    etc...
  end note
else (no)
endif

:Config::apply();
note right
  define(k, v) for k, v in Config::$configMap
end note

stop

@enduml
